### ISSUE TITLE
Get configlet working on Windows (AppVeyor)

### ISSUE THREAD

**Issue by yurrriq** [exercism/xlfe#23]
Related #19

**Comment by kytrinyx** [comment]
Per the twitter conversation here: https://twitter.com/yurrriq/status/701713162983243776

It looks like the problem might be that AppVeyor doesn't support bash, and it is therefore having trouble fetching the configlet binary. The binary is cross-compiled, and so there's a windows version.

Suggested solution: just download the windows binary directly if on AppVeyor.

**Comment by yurrriq** [comment]
:+1: thanks!

**Comment by yurrriq** [comment]
It looks like PowerShell has some weird, awk-like pattern matching syntax. I think with that and the curl we get for free, it can be done. Without access to a Windows machine, I probably won't be taking this on any time soon..

**Comment by kytrinyx** [comment]
> How bad would it be to periodically hardcode the configlet version?

Not too terrible, as long as we remember to update it every once in a while.

**Comment by yurrriq** [comment]
:+1: I can/should also add a pre-commit script the runs the configlet locally.

**Comment by yurrriq** [comment]
I've successfully hardcoded the version as of 02422b28d6fb4c4e7f9ec5eb7db3397a4d0d6b4a. It's unclear to me whether a configlet issue would cause a build failure at this point, but it's a start.

**Comment by kytrinyx** [comment]
:+1:

**Comment by yurrriq** [comment]
Configlet version has been bumped. This needs to be updated accordingly.
