### ISSUE TITLE
Syntax highlighting desires?

### ISSUE THREAD

**Issue by Insti** [exercism/xlfe#40]
There is a current issue open about adding syntax highlighting to tracks that are missing it.
https://github.com/exercism/exercism.io/issues/2988

Exercism uses Rouge for syntax highlighting http://rouge.jneen.net/

Is 'common_lisp' an appropriate highlighter to use for LFE?
If it's not, please look through the examples on the rouge website and let us know what you would like to use instead.

**Comment by yurrriq** [comment]
Common Lisp should be good enough. I can take a look at the Rouge examples, but it will be several days before I'm able. If anyone else wants to jump in, please do!

**Comment by Insti** [comment]
lfe (as common_lisp) syntax highlighting is added in https://github.com/exercism/exercism.io/pull/3004

**Comment by yurrriq** [comment]
Thanks! I think maybe @oubiwann wrote a highlighter once. It might've be for Rouge. I'll let him home in when he can, but `common_lisp` is definitely better than nothing.
