### ISSUE TITLE
Problems API is raising an error on the lfe track

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xlfe#5]
```
Errno::ENOENT at /v2/exercises/lfe
No such file or directory @ rb_sysopen - ./problems/lfe/leap/deps
```

The `deps` file is a symlink to a file in the root of `xlfe`... but that file doesn't exist (presumably because it's in the .gitignore file).

I am temporarily adding an empty deps file so that the API errors stop: ba5fd1f6aedb3652709d2c56ae66ade21892dcfa

**Comment by yurrriq** [comment]
Hmm... Interesting problem. It should be a directory, by the way, and gets filled with LFE dependencies. I added it as a symlink to `../deps` in each of the exercises to avoid unnecessarily redundant copies of `deps` folders. Another quick solution would be to tell each exercise to manage its own `./deps`. What do you think?

It also wouldn't be too terrible to add the `deps` dir to xlfe, I guess..

**Comment by yurrriq** [comment]
Thoughts, @oubiwann?

**Comment by yurrriq** [comment]
I have a WIP solution for this in the [develop](https://github.com/exercism/xlfe/tree/develop) branch.

**Comment by kytrinyx** [comment]
Cool, thanks!

**Comment by yurrriq** [comment]
Should be good to go now.

**Comment by kytrinyx** [comment]
It seems good. If something comes up I'll open a new ticket. Thanks!

**Comment by yurrriq** [comment]
Awesome! Thank you.
